#!/bin/sh
set -eu
mkdir -p aaa
dir=`perl -MCwd=realpath -le'print(realpath(\$ARGV[0]))' -- aaa`
tmux split-window -c "${dir}" -h gdbserver 127.0.0.1:2345 ../em
tmux lastp
cat<<'EOF'>.gdbinit.tmp
# generated by gdb.sh, changes here will be lost
EOF
mv -f .gdbinit.tmp .gdbinit
chmod a-w .gdbinit
exec gdb --quiet --tui \
    -ex 'target remote 127.0.0.1:2345' \
    -ex 'b main' \
    ./em
